src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParticipantRepository::class)
 */
class Participant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $nom_participant;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $prenom_participant;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Resultat::class, mappedBy="participants")
     */
    private $resultats;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="participants")
     */
    private $categories;

    public function __construct()
    {
        $this->resultats = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomParticipant(): ?string
    {
        return $this->nom_participant;
    }

    public function setNomParticipant(?string $nom_participant): self
    {
        $this->nom_participant = $nom_participant;

        return $this;
    }

    public function getPrenomParticipant(): ?string
    {
        return $this->prenom_participant;
    }

    public function setPrenomParticipant(?string $prenom_participant): self
    {
        $this->prenom_participant = $prenom_participant;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection|Resultat[]
     */
    public function getResultats(): Collection
    {
        return $this->resultats;
    }

    public function addResultat(Resultat $resultat): self
    {
        if (!$this->resultats->contains($resultat)) {
            $this->resultats[] = $resultat;
            $resultat->setParticipants($this);
        }

        return $this;
    }

    public function removeResultat(Resultat $resultat): self
    {
        if ($this->resultats->contains($resultat)) {
            $this->resultats->removeElement($resultat);
            // set the owning side to null (unless already changed)
            if ($resultat->getParticipants() === $this) {
                $resultat->setParticipants(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
    
}

src/Form/ParticipantType.php
<?php

namespace App\Form;

use App\Entity\Participant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParticipantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_participant')
            ->add('prenom_participant')
            ->add('sexe')
            ->add('image')
            ->add('email')
            ->add('ville')
            ->add('categories')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Participant::class,
        ]);
    }
}

src/Controller/ParticipantController.php
<?php

namespace App\Controller;

use App\Entity\Participant;
use App\Form\ParticipantType;
use App\Repository\ParticipantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/participant")
 */
class ParticipantController extends AbstractController
{
    /**
     * @Route("/", name="participant_index", methods={"GET"})
     */
    public function index(ParticipantRepository $participantRepository): Response
    {
        return $this->render('participant/index.html.twig', [
            'participants' => $participantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="participant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $participant = new Participant();
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($participant);
            $entityManager->flush();

            return $this->redirectToRoute('participant_index');
        }

        return $this->render('participant/new.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participant_show", methods={"GET"})
     */
    public function show(Participant $participant): Response
    {
        return $this->render('participant/show.html.twig', [
            'participant' => $participant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="participant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Participant $participant): Response
    {
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('participant_index');
        }

        return $this->render('participant/edit.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Participant $participant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($participant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('participant_index');
    }
}

templates/participant/_delete_form.html.twig
<form method="post" action="{{ path('participant_delete', {'id': participant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/participant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/participant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Participant{% endblock %}

{% block body %}
    <h1>Edit Participant</h1>

    {{ include('participant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('participant_index') }}" class="btn btn-primary my-2">back to list</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}

templates/participant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant index{% endblock %}

{% block body %}
    <h1>List of participants</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_participant</th>
                <th>Prenom_participant</th>
                <th>Sexe</th>
                <th>Image</th>
                <th>Email</th>
                <th>Ville</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.nomParticipant }}</td>
                <td>{{ participant.prenomParticipant }}</td>
                <td>{{ participant.sexe }}</td>
                <td>{{ participant.image }}</td>
                <td>{{ participant.email }}</td>
                <td>{{ participant.ville }}</td>
                <td>
                    <a href="{{ path('participant_show', {'id': participant.id}) }}" class="btn btn-success">show</a>
                    <a href="{{ path('participant_edit', {'id': participant.id}) }}" class="btn btn-danger">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('participant_new') }}" class="btn btn-info">Create new</a>
{% endblock %}

templates/participant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Participant{% endblock %}

{% block body %}
    <h1>Create new Participant</h1>

    {{ include('participant/_form.html.twig') }}

    <a href="{{ path('participant_index') }}" class="btn btn-success">back to list</a>
{% endblock %}

templates/participant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant{% endblock %}

{% block body %}
    <h1>Participant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participant.id }}</td>
            </tr>
            <tr>
                <th>Nom_participant</th>
                <td>{{ participant.nomParticipant }}</td>
            </tr>
            <tr>
                <th>Prenom_participant</th>
                <td>{{ participant.prenomParticipant }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ participant.sexe }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ participant.image }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ participant.email }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ participant.ville }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('participant_index') }}" class="btn btn-primary">back to list</a>

    <a href="{{ path('participant_edit', {'id': participant.id}) }}" class="btn btn-danger">edit</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}